[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Housing Package"
version = "0.1.0"
description = "A brief description of your package"
long_description = "file: README.md"
long_description_content_type = "text/markdown"
authors = [
    { name = "Saachi Mohanty", email = "saachi.mohanty@tigeranalytics.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/saachi-tiger/mle-repository"

[project.dependencies]
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
