name: Build and Test as Python module

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tree CLI tool
        run: sudo apt-get install -y tree

      - name: Display directory tree before building
        run: tree

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh
          allow-softlinks: true
          show-channel-urls: true
          use-only-tar-bz2: true
          activate-environment: mle-dev  
          environment-file: env.yml

      - name: Create and activate environment
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a
          conda create -n mle-dev python=3.10
          conda activate mle-dev
        
      - name: Install the package in developer mode
        run: |
          conda activate mle-dev
          pip install -e .

      - name: Install additional dependencies
        run: |
          conda activate mle-dev
          pip install -e .[dev]
      
      - name: Run Tests with Pytest
        run: |
          conda activate mle-dev
          pytest --maxfail=1 --disable-warnings

      - name: Fail if Tests Fail
        if: failure()
        run: exit 1