name: Build Documentation [Assignment 2.8]

on:
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Install Miniforge
        run: |
          wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh
          bash miniforge.sh -b -p $HOME/miniforge3
          source $HOME/miniforge3/etc/profile.d/conda.sh
          conda init bash

      - name: Create Conda environment
        run: |
          source $HOME/miniforge3/etc/profile.d/conda.sh
          conda env create -f env.yml

      - name: Display directory tree before building docs
        run: |
          tree -L 3 docs

      - name: Build Sphinx documentation
        run: |
          source $HOME/miniforge3/etc/profile.d/conda.sh
          conda activate mle-dev
          conda install -y sphinx
          pip install sphinx sphinx_rtd_theme
          cd docs
          make html || { echo "Sphinx build failed"; exit 1; }

      - name: Display directory tree after building docs
        run: |
          tree -L 3 docs/_build || tree -L 3 docs/build

      - name: Upload built documentation
        uses: actions/upload-artifact@v4
        with:
          name: built-docs-html
          path: |
            docs/_build/html
            docs/build/html
