name: Build and Test Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install tree CLI tool
      run: sudo apt-get install -y tree

    - name: Display directory tree before building
      run: tree -L 2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: env.yml
        activate-environment: mle-dev

    - name: Build the package
      run: |
        pip install --upgrade setuptools
        pip install --upgrade build
        python -m build

    - name: Display directory tree after building
      run: tree -L 2

    - name: Install the package
      run: |
        pip install dist/*.whl

    - name: Run tests with pytest
      run: |
        pytest
