name: Build and Test as Python module

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tree CLI tool
        run: sudo apt-get install -y tree

      - name: Display directory tree before building
        run: tree

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh
          auto-activate-base: false
          environment-file: env.yml

      - name: Create Conda environment
        run: |
          source $HOME/miniforge3/etc/profile.d/conda.sh
          conda env create -f env.yml

      - name: Activate Conda environment and install the package in developer mode
        run: |
          source $HOME/miniforge3/etc/profile.d/conda.sh
          conda activate mle-dev
          pip install -e .

      - name: Install additional dependencies
        run: |
          source $HOME/miniforge3/etc/profile.d/conda.sh
          conda activate mle-dev
          pip install -e .[dev]
      
      - name: Run Tests with Pytest
        run: |
          source $HOME/miniforge3/etc/profile.d/conda.sh
          conda activate mle-dev
          conda list
          pytest --maxfail=1 --disable-warnings

      - name: Fail if Tests Fail
        if: failure()
        run: exit 1
