name: Build Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install tree CLI tool
      run: sudo apt-get install -y tree

    - name: Display directory tree before building
      run: tree

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: env.yml
        activate-environment: mle-dev

    - name: Generate requirements.txt
      run: pip freeze > requirements.txt

    - name: Clean up requirements.txt
      run: |
        sed -i '/^.* @ .*$/d' requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install wheel
      run: pip install wheel

    - name: Build the package
      run: python setup.py sdist bdist_wheel

    - name: Display directory tree after building
      run: tree

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/

  build2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: env.yml
        activate-environment: mle-dev

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts

    - name: Verify directory structure
      run: tree dist/

    - name: Install the package
      run: pip install dist/*.whl

    - name: Run nonstandardcode.py
      run: python run-nonstandardcode.py

    - name: Display directory tree after installation
      run: tree
