name: Build and Refactor as Python module

on:
  pull_request:
    branches: 
      - dummy_branches

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tree CLI tool
        run: sudo apt-get install -y tree

      - name: Display directory tree before building
        run: tree

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh
          allow-softlinks: true
          show-channel-urls: true
          use-only-tar-bz2: true
          activate-environment: mle-dev  
          environment-file: env.yml 

      - name: Build the package
        run:  |
          pip install --upgrade setuptools
          pip install --upgrade build
          python -m build

      - name: Display directory tree after building
        run: tree .

      - name: Install package from .whl file
        run: pip install dist/*.whl

      - name: Run installation tests
        run: 
          pytest tests/