name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10
        environment-file: env.yml
        activate-environment: myenv

    - name: Install dependencies
      run: |
        conda run -n myenv pip install flake8

    - name: Run Flake8
      run: |
        conda run -n myenv flake8 .

    - name: Run nonstandardcode.py
      run: |
        conda run -n myenv python nonstandardcode.py
