name: CI pipeline

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Miniconda

        uses: conda-incubator/setup-miniconda@v2

        with:
          activate-environment: mle-dev

          environment-file: env.yml

          python-version: 3.8.18

      - name: Lint with flake8

        run: |

          flake8 .

      - name: Run housing_price.py

        run: |

          python nonstandardcode.py
