name: CI Workflow

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10
        environment-file: env.yml
        activate-environment: base

    - name: Debug Conda Info
      run: |
        conda info
        conda config --show
        conda list

    - name: Remove existing environment
      run: |
        conda env remove -n base || echo "Environment does not exist"

    - name: Install dependencies
      run: |
        conda env update --name base --file env.yml --prune
        conda activate base
        pip install flake8

    - name: Run Flake8
      run: |
        conda activate base
        flake8 .

    - name: Run nonstandardcode.py
      run: |
        conda activate base
        python nonstandardcode.py
